apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-server-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-server-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "delete", "get", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-server-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: job-server-sa
    namespace: default
roleRef:
  kind: Role
  name: job-server-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-server
  template:
    metadata:
      labels:
        app: job-server
    spec:
      serviceAccountName: job-server-sa
      containers:
        - name: job-server
          image: ghcr.io/merlinhelp/junkyard-autograder:latest
          imagePullPolicy: Always
          env:
            - name: KUBECONFIG
              value: "/etc/kubernetes/cluster-b.kubeconfig"
            - name: RUNNER_IMAGE
              value: "docker.io/library/modified-pixelfold-docker:latest"
            - name: GPU_DEVICE_PATH
              value: "/dev/mali0"
            - name: REGISTRY_SECRET_NAME
              value: ""
            # - name: TARGET_WORKER_NODE
            # value: "pf-026"
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: kubeconfig-storage
              mountPath: /etc/kubernetes/cluster-b.kubeconfig
              readOnly: true
      nodeSelector:
          kubernetes.io/arch: arm64
          kubernetes.io/hostname: "pf-022"
      imagePullSecrets:
        - name: my-registry-secret
      volumes:
        - name: kubeconfig-storage
          hostPath:
            path: /home/kalm/cluster-b.kubeconfig
            type: File
---
apiVersion: v1
kind: Service
metadata:
  name: job-server-service
spec:
  type: NodePort
  selector:
    app: job-server
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 30080
